# Blur every window
[[window_rule]]
blur = true

# Place a game on workspace 4
[[window_rule]]
match.app_id = "^steam_app_[0-9]+$"
default_workspace = 4
default_fullscreen = true

# Steam Notifications
[[window_rule]]
default_position = { x = 12, y = 12, anchor = "bottom_right" }
match.title = "^notificationtoasts_\\d+_desktop$"
default_focused = false

# Steam Settings
[[window_rule]]
match.app_id = "^([Ss]team)$"
match.title = "^([Ss]team)$"
default_floating = false

[[window_rule]]
match.app_id = "^([Ss]team)$"
match.title = "^(?![Ss]team$|Friends List$)"
default_floating = true
default_floating_size_px = { width = 1200, height = 900 }

# Steam Friends List
[[window_rule]]
match.title = "Friends List"
focus_on_activate = false
default_scrolling_extent = 0.10

# Dim unfocused windows
[[window_rule]]
match.is_focused = false
opacity = 0.85

[[window_rule]]
match.is_focused = true
opacity = 1.0

# Screen Share Picker
[[window_rule]]
match.app_id = "^dev.noctalia.UmbrielSharePicker$"
default_floating = true
default_floating_size_px = { width = 1200, height = 924 }

# File Picker
[[window_rule]]
match.title = "Open Files"
default_floating = true
default_floating_size_px = { width = 300, height = 900 }

# kitty
 [[window_rule]]
match.app_id = "^kitty$"
default_scrolling_extent = 0.4
