[include]
files = [
"./outputs.toml",
"./inputs.toml",
"./keybinds.toml",
"./layout.toml",
"./window-rules.toml",
"./appearance.toml"    
]

[include.optional]
files = []


[general]
autostart = ["noctalia", "zen-beta"]
mod_key = "Super"
xwayland = false
xwayland_native_resolution = false
show_cheatsheet = false
focus_on_activate = true
honor_restored_maximize = false
