[input]
middle_click_paste = true

[input.keyboard]
layout = "us"
numlock_toggle = true

[input.mouse]
natural_scroll = false
sensitivity = 0.0
scroll_wheel_step = 60

[input.cursor]
theme = "Bibata-Modern-Ice"
size = 22
hardware_cursor = true
follows_focus = true
hide_when_typing = false
hide_timeout_ms = 0

[input.focus]
follows_mouse = true
follows_mouse_max_scroll = 1
